name: Build, Pack, and Publish NuGet Package

on:
  push:
    branches:
      - '*'  # Tüm dallarda yapılan push'lar tetikler
    paths:
      - '**/*'  # Tüm dosya değişiklikleri workflow'u tetikler
env:
  PROJECT_PATH: 'ConsoleApp12/ConsoleApp12.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  build-pack-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Get version from .csproj
        id: version
        run: |
            VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" ConsoleApp12/ConsoleApp12.csproj)
            echo "VERSION=$VERSION" >> $GITHUB_ENV
        

      - name: Restore Dependencies
        run: dotnet restore ConsoleApp12/ConsoleApp12.csproj

      - name: Build LinqApi Project
        run: dotnet build ConsoleApp12/ConsoleApp12.csproj --configuration Release --no-restore



      - name: Pack NuGet Package
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ env.VERSION }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}


      - name: Publish NuGet Package
        run: dotnet nuget push /home/runner/work/ConsoleApp12/ConsoleApp12output/ConsoleApp12.${{ env.VERSION }}.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }} --skip-duplicate